services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - ./mailpit/smpt-users.txt:/data/smpt-users.txt
    command:
      - --smtp-auth-allow-insecure
      - --smtp-auth-file=/data/smpt-users.txt
    restart: unless-stopped
services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - ./mailpit/smpt-users.txt:/data/smpt-users.txt
    command:
      - --smtp-auth-allow-insecure
      - --smtp-auth-file=/data/smpt-users.txt
    restart: unless-stopped